# Generated by Django 4.0.6 on 2022-07-26 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='medicine',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
